runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: numpy
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /api/.*
  script: api.app

- url: /(.+)
  static_files: fastresponse-ui/dist/\1
  upload: fastresponse-ui/dist/.*

- url: /
  static_files: fastresponse-ui/dist/index.html
  upload: app/index.html

